// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package dao

import (
	"lesson/fourth/internal/dao/redis"
)

// Injectors from wire.go:

//go:generate wire
func newTestDao() (*dao, func(), error) {
	clusterClient, cleanup, err := redis.NewRedis()
	if err != nil {
		return nil, nil, err
	}
	daoDao, cleanup2, err := newDao(clusterClient)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return daoDao, func() {
		cleanup2()
		cleanup()
	}, nil
}
